/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    CountTo: typeof import('./src/components/CountTo.vue')['default']
    ECharts: typeof import('./src/components/ECharts.vue')['default']
    Loading: typeof import('./src/components/Loading.vue')['default']
    Locales: typeof import('./src/components/Locales.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ThemePicker: typeof import('./src/components/ThemePicker.vue')['default']
  }
}
